train_image_path: ./DS201/TH1/MNIST/train-images-idx3-ubyte
train_label_path: ./DS201/TH1/MNIST/train-labels.idx1-ubyte
test_image_path: ./DS201/TH1/MNIST/t10k-images.idx3-ubyte
test_label_path: ./DS201/TH1/MNIST/t10k-labels.idx1-ubyte
save_path: ./save
train_batch: 128
val_batch: 128
test_batch: 128
aug: True
patience: 5
image_C:  1
image_W: 28
image_H: 28
model: model_1 # model_1 or model_2
num_classes: 10
learning_rate: 0.0001
num_epochs: 100
best_metric: accuracy