root: './data/cifar10'
save_path: ./save
train_batch: 128
val_batch: 128
test_batch: 128
aug: True
patience: 5
image_C:  3
image_W: 224
image_H: 224
model: resnet18
num_classes: 10
learning_rate: 0.05
num_epochs: 100
best_metric: accuracy
dropout: 0.2
data_name: CIFAR10
train_image_path: /content/DS_102/lab_3/MNIST/train-images.idx3-ubyte
train_label_path: /content/DS_102/lab_3/MNIST/train-labels.idx1-ubyte
test_image_path: /content/DS_102/lab_3/MNIST/t10k-images.idx3-ubyte
test_label_path: /content/DS_102/lab_3/MNIST/t10k-labels.idx1-ubyte