train_image_path: /content/DS_102/lab_3/MNIST/train-images.idx3-ubyte
train_label_path: /content/DS_102/lab_3/MNIST/train-labels.idx1-ubyte
test_image_path: /content/DS_102/lab_3/MNIST/t10k-images.idx3-ubyte
test_label_path: /content/DS_102/lab_3/MNIST/t10k-labels.idx1-ubyte
save_path: ./save
train_batch: 128
val_batch: 128
test_batch: 128
aug: True
patience: 5
image_C:  1
image_W: 28
image_H: 28
model: Lenet
num_classes: 10
learning_rate: 0.0001
num_epochs: 100
best_metric: accuracy
dropout: 0.2
data_name: MNIST