train_image_path: ./DS201/TH2/Fashion_MNIST/train-images-idx3-ubyte
train_label_path: ./DS201/TH2/Fashion_MNIST/train-labels-idx1-ubyte
test_image_path: ./DS201/TH2/Fashion_MNIST/t10k-images-idx3-ubyte
test_label_path: ./DS201/TH2/Fashion_MNIST/t10k-labels-idx1-ubyte
save_path: ./save
train_batch: 128
val_batch: 128
test_batch: 128
aug: True
patience: 5
image_C:  1
image_W: 28
image_H: 28
lambda: 0.01
model: model_3
init_type: ones #one or xavier
regularzation_type: l2 #l1 or l2
momentum: 0.5
optimizer_type: adam #adam or sgd or rmsprop
num_classes: 10
learning_rate: 0.01
num_epochs: 100
best_metric: accuracy