data : Chest-X-Ray
  train_path: ./mnist_png/mnist_png/training
  dev_path: ./mnist_png/mnist_png/testing
  test_path: ./mnist_png/mnist_png/testing
  num_classes: 10
# train_path: ./cifar10/cifar10/train
# test_path: ./cifar10/cifar10/test
save_path: ./save
train_batch: 128
dev_batch: 128
test_batch: 128
num_worker: 2
aug: False
patience: 5
image_C:  3
image_W: 28
image_H: 28
model: bgg19 # vgg19, resnet50
load_pretrained: True

learning_rate: 0.001
num_epochs: 100
best_metric: accuracy